---
- name: Install Clickhouse
  hosts: clickhouse
  become: yes
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  become: yes
  roles:
    - vector-role

- name: Install Lighthouse
  hosts: lighthouse
  become: yes
  roles:
    - lighthouse-role
