---
all:
  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 46.21.246.60
          ansible_user: yc-user
    vector:
      hosts:
        vector-01:
          ansible_host: 93.77.181.157
          ansible_user: yc-user
    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 89.169.157.196
          ansible_user: yc-user
